---
# tasks file for nodejs-systemd

- name: Create node.js instance groups
  group:
    name={{ item.group }}
    system=yes
    state=present
  with_items: '{{ nodejs_instances }}'
  tags: nodejs

- name: Create node.js instance user
  user:
    name={{ item.user }}
    append=yes
    group={{ item.group }}
    shell=/bin/bash
    system=yes
    state=present
  with_items: '{{ nodejs_instances }}'
  tags: nodejs

- name: Checkout app
  git:
    repo={{ item.repo }}
    dest={{ item.dir }}
    version={{ item.version }}
    update={{ item.keep_updated }}
    recursive={{ item.repo_recursive }}
    force=yes
  with_items: '{{ nodejs_instances }}'
  tags: nodejs

- name: Change ownership
  file:
    state=directory
    recurse=yes
    path={{ item.dir }}
    owner={{ item.user }}
    group={{ item.group }}
  with_items: '{{ nodejs_instances }}'
  tags: nodejs

# - name: Run npm install
#   npm: path={{ item.work_dir }}
#   with_items: '{{ nodejs_instances }}'
#   tags: nodejs

- name : Run yarn install
  shell: cd {{ item.work_dir }} && yarn install
  register: yarn_output
  with_items: '{{ nodejs_instances }}'
- debug:
    msg: "status: {{yarn_output}}"

- name : Build project
  shell: cd {{ item.work_dir }} && yarn build
  register: yarn_build
  with_items: '{{ nodejs_instances }}'
- debug:
    msg: "status: {{yarn_build}}"

- name: Install systemd conf
  template: >
    src=systemd.conf.j2
    dest=/etc/systemd/system/app-{{ item.name }}.service
    owner=root
    group=root
    mode=0755
  with_items: '{{ nodejs_instances }}'
  tags: nodejs

- name: Make sure we reload services
  command: systemctl daemon-reload
  tags: nodejs

# - name: Make sure we reload services
#   command: systemctl restart app-{{ item.name }}
#   tags: nodejs

- name: Ensure services are started and enabled on boot
  service: name=app-{{ item.name }} state=restarted enabled=yes
  with_items: '{{ nodejs_instances }}'
  tags: nodejs
