---
- hosts: webserver
  remote_user: dev-user
  become: yes
  become_method: sudo
  gather_facts: no
  
  vars: 
    node_env: "development"
    entry_file: "app.js"
    application_name: "ansible-demo"
    # ansistrano_deploy_to: "/var/www/my-app"
    # ansistrano_version_dir: "releases"
    # ansistrano_current_dir: "current"
    # ansistrano_deploy_via: "git"
    # ansistrano_git_repo: https://github.com/aldomatic/react-circleci-demo.git
    # ansistrano_git_branch: master
    # ansistrano_keep_releases: 0
    # ansistrano_after_update_code_tasks_file: "ansistrano-deploy-tasks/after_update_code_tasks.yml"
    # ansistrano_before_update_code_tasks_file: "ansistrano-deploy-tasks/before_update_code_tasks.yml"
    # ansistrano_after_symlink_tasks_file: "ansistrano-deploy-tasks/after_symlink_tasks.yml"

    # forever_root: '{{ ansistrano_release_path.stdout }}'
    # forever_user: dev-user
    # forever_applications:
    #   - name: "{{application_name}}"
    #     file: "{{ansistrano_release_path.stdout}}/{{entry_file}}"
    #     pid: /var/run/{{application_name}}.pid
    #     log_file: /var/log/{{application_name}}-{{node_env}}.log
    #     env:
    #       NODE_ENV: "{{node_env}}"
    #       PORT: 3000

    nodejs_instances:
      - name: "{{application_name}}"
        description: "{{application_name}} running in {{node_env}} mode."
        repo: https://github.com/aldomatic/react-circleci-demo.git
        version: master
        dir: "/var/www/{{node_env}}/my-app"
        keep_updated: yes
        repo_recursive: yes
        work_dir: "/var/www/{{node_env}}/my-app"
        start: "/usr/bin/node {{entry_file}}"
        stop: ''
        user: dev-user
        group: dev-user
        environment:
          - {name: NODE_ENV, value: "{{node_env}}"}
          - {name: PORT, value: 8989}

  roles: 
    #- { role: "roles/carlosbuenosvinos.ansistrano-deploy" }
    - { role: "roles/ansible-role-nodejs-systemd" }

    