---
- hosts: webserver
  remote_user: dev-user
  become: yes
  become_method: sudo
  gather_facts: no
  
  vars: 
    node_env: "development"
    entry_file: "app.js"
    application_name: "crowdslike-react"

    nodejs_instances:
      - name: "{{application_name}}-{{node_env}}"
        description: "{{application_name}} running in {{node_env}} mode."
        repo: https://github.com/aldomatic/crowdslike-react.git
        version: master
        dir: "/var/www/{{node_env}}/{{application_name}}"
        keep_updated: yes
        repo_recursive: yes
        work_dir: "/var/www/{{node_env}}/{{application_name}}"
        #start: "/usr/bin/node {{entry_file}}"
        start: "/usr/bin/yarn start:prod"
        stop: ''
        user: dev-user
        group: dev-user
        environment:
          - {name: NODE_ENV, value: "{{node_env}}"}
          - {name: PORT, value: 3000}

  roles: 
    - { role: "roles/ansible-role-nodejs-systemd" }

    