---
- hosts: postgres
  remote_user: dev-user
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: ansibledb
    dbuser: devdb
    dbpassword: coolpassword

  tasks:
  - name: ENSURE POSTGRES SERVICE IS RUNNING
    service: name=postgresql
             state=started
             enabled=yes

  - name: ENSURE DATABASE IS CREATED
    postgresql_db: name={{dbname}}
                   encoding='UTF-8'
                   lc_collate='en_US.UTF-8'
                   lc_ctype='en_US.UTF-8'
                   template='template0'
                   state=present

  - name: ENSURE USER HAS ACCESS TO DATABASE
    postgresql_user: db={{dbname}}
                     name={{dbuser}}
                     password={{dbpassword}}
                     priv=ALL
                     state=present

  - name: ENSURE USER DOES NOT HAVE UNNECESSARY PRIVILEGE
    postgresql_user: name={{dbuser}}
                     role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ENSURE NO OTHER USER CAN ACCESS THE DATABSE
    postgresql_privs: db={{dbname}}
                      role=PUBLIC
                      type=database
                      priv=ALL
                      state=absent
